package neu.edu.info6250.entity;
// Generated 2017-12-7 22:48:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bid generated by hbm2java
 */
@Entity
@Table(name = "bid", catalog = "info6250final")
public class Bid implements java.io.Serializable {

	private Integer bidId;
	private Service service;
	private Startup startup;
	private String bidStatus;
	private Date deliverydate;
	private Integer bidAmount;
	private String bidDesc;
	private Set<Report> reports = new HashSet<Report>(0);

	public Bid() {
	}

	public Bid(Service service, Startup startup) {
		this.service = service;
		this.startup = startup;
	}

	public Bid(Service service, Startup startup, String bidStatus, Date deliverydate, Integer bidAmount, String bidDesc,
			Set<Report> reports) {
		this.service = service;
		this.startup = startup;
		this.bidStatus = bidStatus;
		this.deliverydate = deliverydate;
		this.bidAmount = bidAmount;
		this.bidDesc = bidDesc;
		this.reports = reports;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "bid_id", unique = true, nullable = false)
	public Integer getBidId() {
		return this.bidId;
	}

	public void setBidId(Integer bidId) {
		this.bidId = bidId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "serv_id", nullable = false)
	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "su_id", nullable = false)
	public Startup getStartup() {
		return this.startup;
	}

	public void setStartup(Startup startup) {
		this.startup = startup;
	}

	@Column(name = "bid_status", length = 20)
	public String getBidStatus() {
		return this.bidStatus;
	}

	public void setBidStatus(String bidStatus) {
		this.bidStatus = bidStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "deliverydate", length = 10)
	public Date getDeliverydate() {
		return this.deliverydate;
	}

	public void setDeliverydate(Date deliverydate) {
		this.deliverydate = deliverydate;
	}

	@Column(name = "bid_amount")
	public Integer getBidAmount() {
		return this.bidAmount;
	}

	public void setBidAmount(Integer bidAmount) {
		this.bidAmount = bidAmount;
	}

	@Column(name = "bid_desc", length = 100)
	public String getBidDesc() {
		return this.bidDesc;
	}

	public void setBidDesc(String bidDesc) {
		this.bidDesc = bidDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bid")
	public Set<Report> getReports() {
		return this.reports;
	}

	public void setReports(Set<Report> reports) {
		this.reports = reports;
	}

}
