package neu.edu.info6250.entity;
// Generated 2017-12-7 22:48:41 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cc generated by hbm2java
 */
@Entity
@Table(name = "cc", catalog = "info6250final", uniqueConstraints = @UniqueConstraint(columnNames = "card_num"))
public class Cc implements java.io.Serializable {

	private Integer ccId;
	private User user;
	private String cardNum;
	private Integer expirMonth;
	private Integer expirYear;
	private Integer cvv;

	public Cc() {
	}

	public Cc(User user) {
		this.user = user;
	}

	public Cc(User user, String cardNum, Integer expirMonth, Integer expirYear, Integer cvv) {
		this.user = user;
		this.cardNum = cardNum;
		this.expirMonth = expirMonth;
		this.expirYear = expirYear;
		this.cvv = cvv;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cc_id", unique = true, nullable = false)
	public Integer getCcId() {
		return this.ccId;
	}

	public void setCcId(Integer ccId) {
		this.ccId = ccId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "card_num", unique = true, length = 20)
	public String getCardNum() {
		return this.cardNum;
	}

	public void setCardNum(String cardNum) {
		this.cardNum = cardNum;
	}

	@Column(name = "expir_month")
	public Integer getExpirMonth() {
		return this.expirMonth;
	}

	public void setExpirMonth(Integer expirMonth) {
		this.expirMonth = expirMonth;
	}

	@Column(name = "expir_year")
	public Integer getExpirYear() {
		return this.expirYear;
	}

	public void setExpirYear(Integer expirYear) {
		this.expirYear = expirYear;
	}

	@Column(name = "cvv")
	public Integer getCvv() {
		return this.cvv;
	}

	public void setCvv(Integer cvv) {
		this.cvv = cvv;
	}

}
