package neu.edu.info6250.entity;
// Generated 2017-12-7 22:48:41 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Funding generated by hbm2java
 */
@Entity
@Table(name = "funding", catalog = "info6250final")
public class Funding implements java.io.Serializable {

	private Integer fundId;
	private Idea idea;
	private Integer fundValue;
	private String fundDesc;
	private int fundAmount;
	private Set<Orderhistory> orderhistories = new HashSet<Orderhistory>(0);

	public Funding() {
	}

	public Funding(Idea idea, int fundAmount) {
		this.idea = idea;
		this.fundAmount = fundAmount;
	}

	public Funding(Idea idea, Integer fundValue, String fundDesc, int fundAmount, Set<Orderhistory> orderhistories) {
		this.idea = idea;
		this.fundValue = fundValue;
		this.fundDesc = fundDesc;
		this.fundAmount = fundAmount;
		this.orderhistories = orderhistories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "fund_id", unique = true, nullable = false)
	public Integer getFundId() {
		return this.fundId;
	}

	public void setFundId(Integer fundId) {
		this.fundId = fundId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idea_id", nullable = false)
	public Idea getIdea() {
		return this.idea;
	}

	public void setIdea(Idea idea) {
		this.idea = idea;
	}

	@Column(name = "fund_value")
	public Integer getFundValue() {
		return this.fundValue;
	}

	public void setFundValue(Integer fundValue) {
		this.fundValue = fundValue;
	}

	@Column(name = "fund_desc", length = 100)
	public String getFundDesc() {
		return this.fundDesc;
	}

	public void setFundDesc(String fundDesc) {
		this.fundDesc = fundDesc;
	}

	@Column(name = "fund_amount", nullable = false)
	public int getFundAmount() {
		return this.fundAmount;
	}

	public void setFundAmount(int fundAmount) {
		this.fundAmount = fundAmount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "funding")
	public Set<Orderhistory> getOrderhistories() {
		return this.orderhistories;
	}

	public void setOrderhistories(Set<Orderhistory> orderhistories) {
		this.orderhistories = orderhistories;
	}

}
