package neu.edu.info6250.entity;
// Generated 2017-12-7 22:48:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Idea generated by hbm2java
 */
@Entity
@Table(name = "idea", catalog = "info6250final")
public class Idea implements java.io.Serializable {

	private Integer ideaId;
	private Category category;
	private User user;
	private String ideaStatus;
	private Date createdOn;
	private String ideaRemark;
	private String ideaName;
	private String ideaDesc;
	private Date ideaEnddate;
	private int ideaAim;
	private Set<Funding> fundings = new HashSet<Funding>(0);
	private Set<Service> services = new HashSet<Service>(0);

	public Idea() {
	}

	public Idea(Category category, User user, int ideaAim) {
		this.category = category;
		this.user = user;
		this.ideaAim = ideaAim;
	}

	public Idea(Category category, User user, String ideaStatus, Date createdOn, String ideaRemark, String ideaName,
			String ideaDesc, Date ideaEnddate, int ideaAim, Set<Funding> fundings, Set<Service> services) {
		this.category = category;
		this.user = user;
		this.ideaStatus = ideaStatus;
		this.createdOn = createdOn;
		this.ideaRemark = ideaRemark;
		this.ideaName = ideaName;
		this.ideaDesc = ideaDesc;
		this.ideaEnddate = ideaEnddate;
		this.ideaAim = ideaAim;
		this.fundings = fundings;
		this.services = services;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idea_id", unique = true, nullable = false)
	public Integer getIdeaId() {
		return this.ideaId;
	}

	public void setIdeaId(Integer ideaId) {
		this.ideaId = ideaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cate_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "idea_status", length = 20)
	public String getIdeaStatus() {
		return this.ideaStatus;
	}

	public void setIdeaStatus(String ideaStatus) {
		this.ideaStatus = ideaStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_on", length = 10)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "idea_remark", length = 100)
	public String getIdeaRemark() {
		return this.ideaRemark;
	}

	public void setIdeaRemark(String ideaRemark) {
		this.ideaRemark = ideaRemark;
	}

	@Column(name = "idea_name", length = 40)
	public String getIdeaName() {
		return this.ideaName;
	}

	public void setIdeaName(String ideaName) {
		this.ideaName = ideaName;
	}

	@Column(name = "idea_desc", length = 100)
	public String getIdeaDesc() {
		return this.ideaDesc;
	}

	public void setIdeaDesc(String ideaDesc) {
		this.ideaDesc = ideaDesc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "idea_enddate", length = 10)
	public Date getIdeaEnddate() {
		return this.ideaEnddate;
	}

	public void setIdeaEnddate(Date ideaEnddate) {
		this.ideaEnddate = ideaEnddate;
	}

	@Column(name = "idea_aim", nullable = false)
	public int getIdeaAim() {
		return this.ideaAim;
	}

	public void setIdeaAim(int ideaAim) {
		this.ideaAim = ideaAim;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idea")
	public Set<Funding> getFundings() {
		return this.fundings;
	}

	public void setFundings(Set<Funding> fundings) {
		this.fundings = fundings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idea")
	public Set<Service> getServices() {
		return this.services;
	}

	public void setServices(Set<Service> services) {
		this.services = services;
	}

}
