package neu.edu.info6250.entity;
// Generated 2017-12-7 22:48:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orderhistory generated by hbm2java
 */
@Entity
@Table(name = "orderhistory", catalog = "info6250final")
public class Orderhistory implements java.io.Serializable {

	private Integer orderId;
	private Funding funding;
	private User user;
	private String orderStatus;
	private Date createOn;
	private Integer payValue;
	private int buyAmount;

	public Orderhistory() {
	}

	public Orderhistory(Funding funding, User user, String orderStatus, Date createOn, int buyAmount) {
		this.funding = funding;
		this.user = user;
		this.orderStatus = orderStatus;
		this.createOn = createOn;
		this.buyAmount = buyAmount;
	}

	public Orderhistory(Funding funding, User user, String orderStatus, Date createOn, Integer payValue,
			int buyAmount) {
		this.funding = funding;
		this.user = user;
		this.orderStatus = orderStatus;
		this.createOn = createOn;
		this.payValue = payValue;
		this.buyAmount = buyAmount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "order_id", unique = true, nullable = false)
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fund_id", nullable = false)
	public Funding getFunding() {
		return this.funding;
	}

	public void setFunding(Funding funding) {
		this.funding = funding;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "order_status", nullable = false, length = 11)
	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_on", nullable = false, length = 10)
	public Date getCreateOn() {
		return this.createOn;
	}

	public void setCreateOn(Date createOn) {
		this.createOn = createOn;
	}

	@Column(name = "pay_value")
	public Integer getPayValue() {
		return this.payValue;
	}

	public void setPayValue(Integer payValue) {
		this.payValue = payValue;
	}

	@Column(name = "buy_amount", nullable = false)
	public int getBuyAmount() {
		return this.buyAmount;
	}

	public void setBuyAmount(int buyAmount) {
		this.buyAmount = buyAmount;
	}

}
