package neu.edu.info6250.entity;
// Generated 2017-12-7 22:48:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Report generated by hbm2java
 */
@Entity
@Table(name = "report", catalog = "info6250final")
public class Report implements java.io.Serializable {

	private Integer repoId;
	private Bid bid;
	private String repoDesc;
	private Date createdOn;
	private Integer progress;

	public Report() {
	}

	public Report(Bid bid) {
		this.bid = bid;
	}

	public Report(Bid bid, String repoDesc, Date createdOn, Integer progress) {
		this.bid = bid;
		this.repoDesc = repoDesc;
		this.createdOn = createdOn;
		this.progress = progress;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "repo_id", unique = true, nullable = false)
	public Integer getRepoId() {
		return this.repoId;
	}

	public void setRepoId(Integer repoId) {
		this.repoId = repoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bid_id", nullable = false)
	public Bid getBid() {
		return this.bid;
	}

	public void setBid(Bid bid) {
		this.bid = bid;
	}

	@Column(name = "repo_desc", length = 100)
	public String getRepoDesc() {
		return this.repoDesc;
	}

	public void setRepoDesc(String repoDesc) {
		this.repoDesc = repoDesc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_on", length = 10)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "progress")
	public Integer getProgress() {
		return this.progress;
	}

	public void setProgress(Integer progress) {
		this.progress = progress;
	}

}
