package neu.edu.info6250.entity;
// Generated 2017-12-7 22:48:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Service generated by hbm2java
 */
@Entity
@Table(name = "service", catalog = "info6250final")
public class Service implements java.io.Serializable {

	private Integer servId;
	private Idea idea;
	private String servStatus;
	private Date servDdl;
	private Integer reward;
	private String servDesc;
	private Set<Bid> bids = new HashSet<Bid>(0);

	public Service() {
	}

	public Service(Idea idea) {
		this.idea = idea;
	}

	public Service(Idea idea, String servStatus, Date servDdl, Integer reward, String servDesc, Set<Bid> bids) {
		this.idea = idea;
		this.servStatus = servStatus;
		this.servDdl = servDdl;
		this.reward = reward;
		this.servDesc = servDesc;
		this.bids = bids;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "serv_id", unique = true, nullable = false)
	public Integer getServId() {
		return this.servId;
	}

	public void setServId(Integer servId) {
		this.servId = servId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idea_id", nullable = false)
	public Idea getIdea() {
		return this.idea;
	}

	public void setIdea(Idea idea) {
		this.idea = idea;
	}

	@Column(name = "serv_status", length = 20)
	public String getServStatus() {
		return this.servStatus;
	}

	public void setServStatus(String servStatus) {
		this.servStatus = servStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "serv_ddl", length = 10)
	public Date getServDdl() {
		return this.servDdl;
	}

	public void setServDdl(Date servDdl) {
		this.servDdl = servDdl;
	}

	@Column(name = "reward")
	public Integer getReward() {
		return this.reward;
	}

	public void setReward(Integer reward) {
		this.reward = reward;
	}

	@Column(name = "serv_desc", length = 100)
	public String getServDesc() {
		return this.servDesc;
	}

	public void setServDesc(String servDesc) {
		this.servDesc = servDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "service")
	public Set<Bid> getBids() {
		return this.bids;
	}

	public void setBids(Set<Bid> bids) {
		this.bids = bids;
	}

}
