package neu.edu.info6250.entity;
// Generated 2017-12-7 22:48:41 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Startup generated by hbm2java
 */
@Entity
@Table(name = "startup", catalog = "info6250final")
public class Startup implements java.io.Serializable {

	private Integer suId;
	private Category category;
	private User user;
	private String suName;
	private String compName;
	private Set<Bid> bids = new HashSet<Bid>(0);

	public Startup() {
	}

	public Startup(Category category, User user) {
		this.category = category;
		this.user = user;
	}

	public Startup(Category category, User user, String suName, String compName, Set<Bid> bids) {
		this.category = category;
		this.user = user;
		this.suName = suName;
		this.compName = compName;
		this.bids = bids;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "su_id", unique = true, nullable = false)
	public Integer getSuId() {
		return this.suId;
	}

	public void setSuId(Integer suId) {
		this.suId = suId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cate_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "su_name", length = 20)
	public String getSuName() {
		return this.suName;
	}

	public void setSuName(String suName) {
		this.suName = suName;
	}

	@Column(name = "comp_name", length = 20)
	public String getCompName() {
		return this.compName;
	}

	public void setCompName(String compName) {
		this.compName = compName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "startup")
	public Set<Bid> getBids() {
		return this.bids;
	}

	public void setBids(Set<Bid> bids) {
		this.bids = bids;
	}

}
